# Generated by Django 5.1.6 on 2026-08-02 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120, unique=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('embedding_dimension', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('canonical_name',),
            },
        ),
        migrations.CreateModel(
            name='HHVacancySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='hh', max_length=30)),
                ('external_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('employer', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('raw_skills', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-fetched_at'),
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_vacancy_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено')], default='active', max_length=20)),
                ('interview_rag_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('current_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_interviews', to='candidate_trainer.skill')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assistant', 'Интервьюер'), ('user', 'Кандидат')], max_length=20)),
                ('content', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidate_trainer.interviewsession')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_messages', to='candidate_trainer.skill')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('skill_core', 'Навыки'), ('interview', 'Собеседование'), ('user_analytics', 'Аналитика пользователя')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('embedding_dimension', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'title'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('hh', 'HH.ru'), ('imported', 'Импортированный документ'), ('verified', 'Проверенный материал'), ('generated', 'Сгенерированный материал'), ('interview', 'Материал для интервью'), ('user_analytics', 'Пользовательская аналитика')], max_length=30)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidate_trainer.knowledgecollection')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('embedding_dimension', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='candidate_trainer.knowledgedocument')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_chunks', to='candidate_trainer.skill')),
            ],
            options={
                'ordering': ('document', 'chunk_index'),
            },
        ),
        migrations.CreateModel(
            name='InterviewInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('depth', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('practical_application', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_insights', to=settings.AUTH_USER_MODEL)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answer_insight', to='candidate_trainer.interviewmessage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_insights', to='candidate_trainer.interviewmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='candidate_trainer.interviewsession')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_insights', to='candidate_trainer.skill')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnalysisSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_count', models.PositiveSmallIntegerField()),
                ('frequency_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rank', models.PositiveSmallIntegerField()),
                ('variants', models.JSONField(default=list)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_occurrences', to='candidate_trainer.skill')),
            ],
            options={
                'ordering': ('rank', 'skill__canonical_name'),
            },
        ),
        migrations.CreateModel(
            name='SkillExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='candidate_trainer.analysisskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VacancyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('normalized_query', models.CharField(max_length=200)),
                ('area_id', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=120)),
                ('cache_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('vacancies_found', models.PositiveSmallIntegerField(default=0)),
                ('vacancies_processed', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_analyses', to=settings.AUTH_USER_MODEL)),
                ('vacancies', models.ManyToManyField(blank=True, related_name='analyses', to='candidate_trainer.hhvacancysnapshot')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='candidate_trainer.vacancyanalysis'),
        ),
        migrations.AddField(
            model_name='analysisskill',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_skills', to='candidate_trainer.vacancyanalysis'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollection',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_owner_knowledge_collection'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_global_knowledge_collection'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['collection', 'external_id'], name='candidate_t_collect_429079_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['skill', 'embedding_model'], name='candidate_t_skill_i_529350_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'),
        ),
        migrations.AddConstraint(
            model_name='interviewmessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_interview_message_sequence'),
        ),
        migrations.AddIndex(
            model_name='vacancyanalysis',
            index=models.Index(fields=['user', 'status', '-created_at'], name='candidate_t_user_id_8180be_idx'),
        ),
        migrations.AddConstraint(
            model_name='vacancyanalysis',
            constraint=models.UniqueConstraint(fields=('user', 'cache_key'), name='unique_candidate_analysis_cache'),
        ),
        migrations.AddConstraint(
            model_name='analysisskill',
            constraint=models.UniqueConstraint(fields=('analysis', 'skill'), name='unique_skill_per_analysis'),
        ),
    ]
